# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import phonebook_pb2 as phonebook__pb2


class PhoneBookStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAll = channel.unary_unary(
                '/PhoneBook/GetAll',
                request_serializer=phonebook__pb2.Empty.SerializeToString,
                response_deserializer=phonebook__pb2.ContacsList.FromString,
                )
        self.Get = channel.unary_unary(
                '/PhoneBook/Get',
                request_serializer=phonebook__pb2.ID.SerializeToString,
                response_deserializer=phonebook__pb2.Contact.FromString,
                )
        self.Create = channel.unary_unary(
                '/PhoneBook/Create',
                request_serializer=phonebook__pb2.Contact.SerializeToString,
                response_deserializer=phonebook__pb2.Contact.FromString,
                )
        self.Update = channel.unary_unary(
                '/PhoneBook/Update',
                request_serializer=phonebook__pb2.Contact.SerializeToString,
                response_deserializer=phonebook__pb2.Contact.FromString,
                )
        self.Remove = channel.unary_unary(
                '/PhoneBook/Remove',
                request_serializer=phonebook__pb2.ID.SerializeToString,
                response_deserializer=phonebook__pb2.Empty.FromString,
                )


class PhoneBookServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhoneBookServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAll': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=phonebook__pb2.Empty.FromString,
                    response_serializer=phonebook__pb2.ContacsList.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=phonebook__pb2.ID.FromString,
                    response_serializer=phonebook__pb2.Contact.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=phonebook__pb2.Contact.FromString,
                    response_serializer=phonebook__pb2.Contact.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=phonebook__pb2.Contact.FromString,
                    response_serializer=phonebook__pb2.Contact.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=phonebook__pb2.ID.FromString,
                    response_serializer=phonebook__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PhoneBook', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PhoneBook(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PhoneBook/GetAll',
            phonebook__pb2.Empty.SerializeToString,
            phonebook__pb2.ContacsList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PhoneBook/Get',
            phonebook__pb2.ID.SerializeToString,
            phonebook__pb2.Contact.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PhoneBook/Create',
            phonebook__pb2.Contact.SerializeToString,
            phonebook__pb2.Contact.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PhoneBook/Update',
            phonebook__pb2.Contact.SerializeToString,
            phonebook__pb2.Contact.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PhoneBook/Remove',
            phonebook__pb2.ID.SerializeToString,
            phonebook__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
